---
services:
    app:
        build: ./build
        hostname: "${COMPOSE_PROJECT_NAME}-app"
        container_name: "${COMPOSE_PROJECT_NAME}_app"
        volumes:
            - ".:/app"

        env_file: ./.env.app
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

volumes:
    db-data: ~
