---
services:
    app:
        build: .
        image: bravepickle/jirassic-park:latest
        hostname: "${COMPOSE_PROJECT_NAME}-app"
        container_name: "${COMPOSE_PROJECT_NAME}_app"
        # ports:
        #     - "8000:80"
        #     - "8443:443"
        env_file: ./.env.app
        command: "/app/jirassic-park -env .env -debug"
        volumes:
            - "./view:/app/view:ro"
            - "./.env.app:/app/.env:ro"
        depends_on:
            - proxy
        labels:
            - "traefik.enable=true"

            # Middleware CORS headers - more dynamic ones than the rest
            - "traefik.http.middlewares.web-cors.headers.accessControlAllowMethods=GET,OPTIONS,PUT,DELETE,POST"
            - "traefik.http.middlewares.web-cors.headers.accessControlAllowOriginList=*"
            # - "traefik.http.middlewares.web-cors.headers.accessControlAllowOriginList=https://${APP_HOST},https://localhost,https://127.0.0.1,https://${APP_HOST}:9443,https://localhost:9443,https://127.0.0.1:9443"
            - "traefik.http.middlewares.web-cors.headers.accessControlMaxAge=100"
            - "traefik.http.middlewares.web-cors.headers.accessControlAllowCredentials=true"
            - "traefik.http.middlewares.web-cors.headers.accessControlExposeHeaders=*"
            - "traefik.http.middlewares.web-cors.headers.accessControlAllowHeaders=*"
            - "traefik.http.middlewares.web-cors.headers.addVaryHeader=true"
            # - "traefik.http.middlewares.web-cors.headers.allowedHosts=${APP_HOST},localhost,127.0.0.1"

            # Routers
            - "traefik.http.routers.app.tls=true"
            - "traefik.http.routers.app.entryPoints=webSecured"
            - "traefik.http.routers.app.rule=Host(`${APP_HOST}`, `localhost`)"
            # - "traefik.http.routers.app.rule=Host(`${APP_HOST}`, `localhost`) && PathPrefix(`/app`)"
            # - "traefik.http.routers.app.middlewares=default-headers@file,app-prefix@file,web-cors@docker"
            - "traefik.http.routers.app.middlewares=default-headers@file,web-cors@docker"
        profiles:
            - main
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    proxy:
        image: traefik:v2.10
        hostname: "${COMPOSE_PROJECT_NAME}-proxy"
        container_name: "${COMPOSE_PROJECT_NAME}_proxy"
        ports:
            - "9000:80" # Default HTTP port
            - "9443:443" # Default HTTPS port
            - "9080:8080" # The web UI
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./etc/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro"
            - "./etc/traefik/dynamic.conf.yaml:/etc/traefik/dynamic.conf.yaml:ro"
            - "./var/server.crt:/etc/ssl/certs/server.crt:ro"
            - "./var/server.key:/etc/ssl/private/server.key:ro"
        profiles:
            - main
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

    whoami:
        image: traefik/whoami
        hostname: "${COMPOSE_PROJECT_NAME}-whoami"
        container_name: "${COMPOSE_PROJECT_NAME}_whoami"
        profiles:
            - debug
        depends_on:
            - proxy
        labels:
            - "traefik.enable=true"

            # Routers
            - "traefik.http.routers.whoami.tls=true"
            - "traefik.http.routers.whoami.priority=4"
            - "traefik.http.routers.whoami.rule=Host(`${APP_HOST}`, `localhost`) && PathPrefix(`/whoami`)"
            - "traefik.http.routers.whoami.entryPoints=webSecured"
            - "traefik.http.routers.whoami.middlewares=default-headers@file"
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"
