---
services:
    app:
        build: .
        hostname: "${COMPOSE_PROJECT_NAME}-app"
        container_name: "${COMPOSE_PROJECT_NAME}_app"
        ports:
            -
        env_file: ./.env.app
        logging:
            driver: "json-file"
            options:
                max-size: "200k"
                max-file: "3"

