# Settings for dynamic config file provider
# See https://doc.traefik.io/traefik/providers/file/

# Self-signed SSL certificates can be defined only using file provider
tls:
    certificates:
        -   certFile: /etc/ssl/certs/server.crt
            keyFile: /etc/ssl/private/server.key


    stores:
        default:
            defaultCertificate:
                certFile: /etc/ssl/certs/server.crt
                keyFile: /etc/ssl/private/server.key

    options:
        default:
            alpnProtocols:
                - http/1.1
                - h2

http:
    services:
        jira-service:
            loadBalancer:
                servers:
                    - url: ${APP_JIRA_BASE_URI}
                passHostHeader: false
#
    routers:
        jira-route:
            tls: true
            service: jira-service
            entryPoints:
                - webSecured
            middlewares:
                - default-headers
                - jira-prefix

            rule: "Host(`localhost`, `jirassic.localhost`) && PathPrefix(`/jira`)"

    middlewares:
        jira-prefix:
            stripPrefix:
                prefixes: /jira

        app-prefix:
            stripPrefix:
                prefixes: /app

        default-headers:
            headers:
                frameDeny: true
                browserXssFilter: true
                contentTypeNosniff: true
                forceSTSHeader: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 5000
                customFrameOptionsValue: SAMEORIGIN
                addVaryHeader: true
                isDevelopment: true

